// 1. DỮ LIỆU 29 CHỮ CÁI TIẾNG VIỆT
const ALPHABET_DATA = [
    { id: "a", name: "Chữ A", upper: "A", lower: "a", youtubeId: "qeVv7ApZr1I", description: "Gồm nét cong kín và nét móc ngược phải." },
    { id: "aw", name: "Chữ Ă", upper: "Ă", lower: "ă", youtubeId: "1inzb8uiVio", description: "Chữ 'a' kết hợp với dấu nón ngửa (á) ở trên." },
    { id: "aa", name: "Chữ Â", upper: "Â", lower: "â", youtubeId: "2hjEJp9L1rM", description: "Chữ 'a' kết hợp với dấu mũ (ô) úp ở trên." },
    { id: "b", name: "Chữ B", upper: "B", lower: "b", youtubeId: "ZutfvPYwK40", description: "Gồm nét khuyết trên nối liền nét thắt trên." },
    { id: "c", name: "Chữ C", upper: "C", lower: "c", youtubeId: "9Xekg3rU7sc", description: "Nét cong hở phải cao 2 ô li." },
    { id: "d", name: "Chữ D", upper: "D", lower: "d", youtubeId: "dfbBiT2aAYs", description: "Gồm nét cong kín và nét móc ngược phải cao 4 ô li." },
    { id: "dd", name: "Chữ Đ", upper: "Đ", lower: "đ", youtubeId: "LYJ_MVg5Ggs", description: "Chữ 'd' có thêm nét gạch ngang ngắn ở đường kẻ 3." },
    { id: "e", name: "Chữ E", upper: "E", lower: "e", youtubeId: "IEdfR38gcjo", description: "Nét cong xiên lên rồi vòng sang trái tạo nét cong hở phải." },
    { id: "ee", name: "Chữ Ê", upper: "Ê", lower: "ê", youtubeId: "OZ98t9hNipo", description: "Chữ 'e' thêm dấu mũ úp trên đầu." },
    { id: "g", name: "Chữ G", upper: "G", lower: "g", youtubeId: "oTDP5kYTd6o", description: "Gồm nét cong kín và nét khuyết dưới cao 5 ô li." },
    { id: "h", name: "Chữ H", upper: "H", lower: "h", youtubeId: "KM3cqrhKeSw", description: "Gồm nét khuyết trên và nét móc hai đầu." },
    { id: "i", name: "Chữ I", upper: "I", lower: "i", youtubeId: "h7YOnn63EQU", description: "Gồm nét xiên ngắn, nét móc ngược và chấm nhỏ trên đầu." },
    { id: "k", name: "Chữ K", upper: "K", lower: "k", youtubeId: "X3YNUW3q_7A", description: "Gồm nét khuyết trên và nét thắt giữa." },
    { id: "l", name: "Chữ L", upper: "L", lower: "l", youtubeId: "xVstl9bH2_o", description: "Nét khuyết trên nối liền nét móc ngược cao 5 ô li." },
    { id: "m", name: "Chữ M", upper: "M", lower: "m", youtubeId: "qeVv7ApZr1I", description: "Gồm 1 nét móc xuôi ngắn, 1 nét móc xuôi rộng và 1 nét móc hai đầu." },
    { id: "n", name: "Chữ N", upper: "N", lower: "n", youtubeId: "1inzb8uiVio", description: "Gồm 1 nét móc xuôi ngắn và 1 nét móc hai đầu." },
    { id: "o", name: "Chữ O", upper: "O", lower: "o", youtubeId: "2hjEJp9L1rM", description: "Nét cong khép kín cao 2 ô li." },
    { id: "oo", name: "Chữ Ô", upper: "Ô", lower: "ô", youtubeId: "ZutfvPYwK40", description: "Chữ 'o' thêm dấu mũ úp trên đầu." },
    { id: "ow", name: "Chữ Ơ", upper: "Ơ", lower: "ơ", youtubeId: "9Xekg3rU7sc", description: "Chữ 'o' thêm nét râu nhỏ bên phải." },
    { id: "p", name: "Chữ P", upper: "P", lower: "p", youtubeId: "dfbBiT2aAYs", description: "Gồm nét xiên ngắn, nét sổ thẳng cao 4 ô li và nét móc hai đầu." },
    { id: "q", name: "Chữ Q", upper: "Q", lower: "q", youtubeId: "LYJ_MVg5Ggs", description: "Gồm nét cong kín và nét sổ thẳng cao 4 ô li." },
    { id: "r", name: "Chữ R", upper: "R", lower: "r", youtubeId: "IEdfR38gcjo", description: "Gồm nét xiên thắt ở đỉnh nối liền nét cong hở phải." },
    { id: "s", name: "Chữ S", upper: "S", lower: "s", youtubeId: "OZ98t9hNipo", description: "Nét xiên thắt ở đỉnh lượn xoắn vào trong." },
    { id: "t", name: "Chữ T", upper: "T", lower: "t", youtubeId: "oTDP5kYTd6o", description: "Gồm nét xiên ngắn, nét móc ngược cao 3 ô li và gạch ngang ngắn." },
    { id: "u", name: "Chữ U", upper: "U", lower: "u", youtubeId: "KM3cqrhKeSw", description: "Gồm nét xiên ngắn, nét móc hai đầu rộng và nét móc ngược." },
    { id: "uw", name: "Chữ Ư", upper: "Ư", lower: "ư", youtubeId: "h7YOnn63EQU", description: "Chữ 'u' thêm nét râu nhỏ bên phải." },
    { id: "v", name: "Chữ V", upper: "V", lower: "v", youtubeId: "X3YNUW3q_7A", description: "Gồm nét móc hai đầu và nét thắt nhỏ ở đỉnh." },
    { id: "x", name: "Chữ X", upper: "X", lower: "x", youtubeId: "xVstl9bH2_o", description: "Gồm nét cong hở phải và nét cong hở trái tựa lưng vào nhau." },
    { id: "y", name: "Chữ Y", upper: "Y", lower: "y", youtubeId: "qeVv7ApZr1I", description: "Gồm nét xiên ngắn, nét móc hai đầu và nét khuyết dưới." }
];

// 2. DỮ LIỆU 14 NÉT CƠ BẢN
const BASIC_STROKES_DATA = [
    { id: "sothang", name: "Nét sổ thẳng", char: "|", youtubeId: "qeVv7ApZr1I", description: "Đặt bút trên đường kẻ ngang 3, kéo thẳng xuống đường kẻ 1." },
    { id: "ngang", name: "Nét ngang", char: "—", youtubeId: "1inzb8uiVio", description: "Đặt bút trên đường kẻ 2, đưa bút từ trái sang phải." },
    { id: "xientrai", name: "Nét xiên trái", char: "╱", youtubeId: "2hjEJp9L1rM", description: "Đặt bút ở đường kẻ 3, kéo chéo xuống góc trái đường kẻ 1." },
    { id: "xienphai", name: "Nét xiên phải", char: "╲", youtubeId: "ZutfvPYwK40", description: "Đặt bút ở đường kẻ 3, kéo chéo xuống góc phải đường kẻ 1." },
    { id: "mocxuoi", name: "Nét móc xuôi", char: "∩", youtubeId: "9Xekg3rU7sc", description: "Đặt bút giữa ô li 2 và 3, vòng cong lên đường kẻ 3 rồi kéo thẳng xuống." },
    { id: "mocnguoc", name: "Nét móc ngược", char: "∪", youtubeId: "dfbBiT2aAYs", description: "Đặt bút ở đường kẻ 3, kéo thẳng xuống rồi lượn cong hất lên." },
    { id: "moc2dau", name: "Nét móc hai đầu", char: "ʃ", youtubeId: "LYJ_MVg5Ggs", description: "Đặt bút ở đường kẻ 2, lượn cong lên đường kẻ 3 rồi kéo xuống móc hất lên." },
    { id: "conghotrai", name: "Nét cong hở trái", char: "⊃", youtubeId: "IEdfR38gcjo", description: "Đặt bút dưới đường kẻ 3, lượn cong sang phải xuống đường kẻ 1." },
    { id: "conghophai", name: "Nét cong hở phải", char: "⊂", youtubeId: "OZ98t9hNipo", description: "Đặt bút dưới đường kẻ 3, lượn cong sang trái xuống đường kẻ 1." },
    { id: "congkin", name: "Nét cong khép kín", char: "O", youtubeId: "oTDP5kYTd6o", description: "Đặt bút dưới đường kẻ 3, viết nét cong khép kín tròn trịa." },
    { id: "khuyettren", name: "Nét khuyết trên", char: "l", youtubeId: "KM3cqrhKeSw", description: "Đặt bút đường kẻ 2, kéo xiên lên đường kẻ 6 rồi vòng xuống đường kẻ 1." },
    { id: "khuyetduoi", name: "Nét khuyết dưới", char: "g", youtubeId: "h7YOnn63EQU", description: "Kéo thẳng xuống dưới đường kẻ 1 (3 ô li), lượn cong hất xiên lên." },
    { id: "thattren", name: "Nét thắt trên", char: "r", youtubeId: "X3YNUW3q_7A", description: "Đặt bút đường kẻ 1, đưa lên đường kẻ 3 xoắn một vòng nhỏ thắt lại." },
    { id: "thatgiua", name: "Nét thắt giữa", char: "k", youtubeId: "xVstl9bH2_o", description: "Viết nét khuyết, đến đường kẻ 2 xoắn vòng thắt nhỏ rồi kéo ra." }
];
