// Dữ liệu 29 Chữ cái Tiếng Việt (kèm Youtube ID chuẩn)
const ALPHABET_DATA = [
    { id: "a", name: "Chữ A", char: "a", upper: "A", lower: "a", youtubeId: "3m0Yy9x1p8A", description: "Chữ a gồm 2 nét: nét cong kín và nét móc ngược phải." },
    { id: "aw", name: "Chữ Ă", char: "ă", upper: "Ă", lower: "ă", youtubeId: "8xI4_1j7E58", description: "Chữ ă viết như chữ a, thêm nét cong dưới (á) ở trên đầu." },
    { id: "aa", name: "Chữ Â", char: "â", upper: "Â", lower: "â", youtubeId: "k_2Gf4M_0_g", description: "Chữ â viết như chữ a, thêm dấu nón (mũ) úp xuống ở trên đầu." },
    { id: "b", name: "Chữ B", char: "b", upper: "B", lower: "b", youtubeId: "9S_pGq4j_X0", description: "Chữ b gồm nét khuyết trên nối liền với nét thắt trên." },
    { id: "c", name: "Chữ C", char: "c", upper: "C", lower: "c", youtubeId: "L9jW0QpX_8E", description: "Chữ c gồm 1 nét cong hở phải." },
    { id: "d", name: "Chữ D", char: "d", upper: "D", lower: "d", youtubeId: "0I9Z_q1n83s", description: "Chữ d gồm nét cong kín và nét móc ngược phải cao 4 ô ly." },
    { id: "dd", name: "Chữ Đ", char: "đ", upper: "Đ", lower: "đ", youtubeId: "G7m8k_p9R0s", description: "Chữ đ viết như chữ d, thêm nét gạch ngang ngắn ở thân." },
    { id: "e", name: "Chữ E", char: "e", upper: "E", lower: "e", youtubeId: "5mR9_0L_q8A", description: "Chữ e gồm nét cong hở phải kết hợp nét thắt giữa." },
    { id: "ee", name: "Chữ Ê", char: "ê", upper: "Ê", lower: "ê", youtubeId: "xR4p8_L2P_s", description: "Chữ ê viết như chữ e, thêm dấu mũ trên đầu." },
    { id: "g", name: "Chữ G", char: "g", upper: "G", lower: "g", youtubeId: "P_9x1m8Q_7s", description: "Chữ g gồm nét cong kín và nét khuyết dưới." },
    { id: "h", name: "Chữ H", char: "h", upper: "H", lower: "h", youtubeId: "1m2N3p4Q5R6", description: "Chữ h gồm nét khuyết trên và nét móc hai đầu." },
    { id: "i", name: "Chữ I", char: "i", upper: "I", lower: "i", youtubeId: "789_aBcDeFg", description: "Chữ i gồm nét xiên ngắn, nét móc ngược phải và dấu chấm nhỏ." },
    { id: "k", name: "Chữ K", char: "k", upper: "K", lower: "k", youtubeId: "HijKlMnOpQr", description: "Chữ k gồm nét khuyết trên và nét thắt giữa." },
    { id: "l", name: "Chữ L", char: "l", upper: "L", lower: "l", youtubeId: "sTuVwXyZaBc", description: "Chữ l gồm nét khuyết trên nối liền nét móc ngược phải cao 5 ô ly." },
    { id: "m", name: "Chữ M", char: "m", upper: "M", lower: "m", youtubeId: "dEfGhIjKlMn", description: "Chữ m gồm nét móc xuôi ngắn, nét móc xuôi rộng và nét móc hai đầu." },
    { id: "n", name: "Chữ N", char: "n", upper: "N", lower: "n", youtubeId: "OpQrStUvWxY", description: "Chữ n gồm nét móc xuôi ngắn và nét móc hai đầu." },
    { id: "o", name: "Chữ O", char: "o", upper: "O", lower: "o", youtubeId: "zAbCdEfGhIj", description: "Chữ o gồm 1 nét cong kín hình quả trứng đứng." },
    { id: "oo", name: "Chữ Ô", char: "ô", upper: "Ô", lower: "ô", youtubeId: "KlMnOpQrStU", description: "Chữ ô viết như chữ o, thêm dấu mũ nón trên đầu." },
    { id: "ow", name: "Chữ Ơ", char: "ơ", upper: "Ơ", lower: "ơ", youtubeId: "vWxYzAbCdEf", description: "Chữ ơ viết như chữ o, thêm râu nhỏ ở góc trên bên phải." },
    { id: "p", name: "Chữ P", char: "p", upper: "P", lower: "p", youtubeId: "GhIjKlMnOpQ", description: "Chữ p gồm nét xiên ngắn, nét thẳng đứng và nét móc hai đầu." },
    { id: "q", name: "Chữ Q", char: "q", upper: "Q", lower: "q", youtubeId: "rStUvWxYzAb", description: "Chữ q gồm nét cong kín và nét thẳng đứng dài 4 ô ly." },
    { id: "r", name: "Chữ R", char: "r", upper: "R", lower: "r", youtubeId: "CdEfGhIjKlM", description: "Chữ r gồm nét thắt trên và nét móc ngược phải." },
    { id: "s", name: "Chữ S", char: "s", upper: "S", lower: "s", youtubeId: "nOpQrStUvWx", description: "Chữ s gồm nét thắt trên nghiêng và nét cong hở trái." },
    { id: "t", name: "Chữ T", char: "t", upper: "T", lower: "t", youtubeId: "YzAbCdEfGhI", description: "Chữ t gồm nét xiên ngắn, nét móc ngược dài và nét gạch ngang." },
    { id: "u", name: "Chữ U", char: "u", upper: "U", lower: "u", youtubeId: "jKlMnOpQrSt", description: "Chữ u gồm nét móc ngược rộng và nét móc ngược hẹp." },
    { id: "uw", name: "Chữ Ư", char: "ư", upper: "Ư", lower: "ư", youtubeId: "UvWxYzAbCdE", description: "Chữ ư viết như chữ u, thêm râu nhỏ ở nét móc ngược thứ hai." },
    { id: "v", name: "Chữ V", char: "v", upper: "V", lower: "v", youtubeId: "fGhIjKlMnOp", description: "Chữ v gồm nét móc hai đầu và nét thắt trên." },
    { id: "x", name: "Chữ X", char: "x", upper: "X", lower: "x", youtubeId: "QrStUvWxYzA", description: "Chữ x gồm nét cong hở phải lưng tựa nét cong hở trái." },
    { id: "y", name: "Chữ Y", char: "y", upper: "Y", lower: "y", youtubeId: "bCdEfGhIjKl", description: "Chữ y gồm nét xiên ngắn, nét móc ngược và nét khuyết dưới." }
];

// Dữ liệu 14 Nét cơ bản
const BASIC_STROKES_DATA = [
    { id: "sothang", name: "Nét thẳng", char: "│", youtubeId: "3m0Yy9x1p8A", description: "Đặt bút ở đường kẻ ngang 3, kéo thẳng xuống đường kẻ ngang 1." },
    { id: "songang", name: "Nét ngang", char: "─", youtubeId: "8xI4_1j7E58", description: "Đặt bút ở đường kẻ 2, đưa ngang sang phải 2 ô ly." },
    { id: "soxienphai", name: "Nét xiên phải", char: "╱", youtubeId: "k_2Gf4M_0_g", description: "Kéo xiên từ trên xuống dưới, từ phải sang trái." },
    { id: "soxientrai", name: "Nét xiên trái", char: "╲", youtubeId: "9S_pGq4j_X0", description: "Kéo xiên từ trên xuống dưới, từ trái sang phải." },
    { id: "mocnguoc", name: "Nét móc ngược", char: "⌋", youtubeId: "L9jW0QpX_8E", description: "Kéo thẳng xuống gần đường kẻ 1 thì lượn cong sang phải." },
    { id: "mocxuoi", name: "Nét móc xuôi", char: "⌊", youtubeId: "0I9Z_q1n83s", description: "Lượn cong từ dưới lên rồi kéo thẳng xuống." },
    { id: "mochaiđau", name: "Nét móc 2 đầu", char: "⎰", youtubeId: "G7m8k_p9R0s", description: "Lượng móc xuôi nối liền nét móc ngược." },
    { id: "conghophai", name: "Nét cong hở phải", char: "⊂", youtubeId: "5mR9_0L_q8A", description: "Cong từ phải sang trái, mở về bên phải." },
    { id: "conghotrai", name: "Nét cong hở trái", char: "⊃", youtubeId: "xR4p8_L2P_s", description: "Cong từ trái sang phải, mở về bên trái." },
    { id: "congkin", name: "Nét cong kín", char: "○", youtubeId: "P_9x1m8Q_7s", description: "Viết tròn đều hình quả trứng đứng." },
    { id: "khuyettren", name: "Nét khuyết trên", char: "ʃ", youtubeId: "1m2N3p4Q5R6", description: "Kéo xiên lên lượn cong đầu rồi kéo thẳng xuống." },
    { id: "khuyetduoi", name: "Nét khuyết dưới", char: "ʅ", youtubeId: "789_aBcDeFg", description: "Kéo thẳng xuống dưới đường kẻ 1 rồi lượn vồng lên." },
    { id: "that", name: "Nét thắt", char: "ɤ", youtubeId: "HijKlMnOpQr", description: "Tạo vòng xoắn thắt nhỏ ở giữa hoặc trên." },
    { id: "song", name: "Nét lượn", char: "〰", youtubeId: "sTuVwXyZaBc", description: "Lượn mềm mại như sóng nước." }
];
